# Generated by Django 4.1.7 on 2023-04-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("cid", models.IntegerField(primary_key=True, serialize=False)),
                ("cname", models.CharField(max_length=100)),
                ("tname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("sid", models.IntegerField(primary_key=True, serialize=False)),
                ("sname", models.CharField(max_length=100)),
                ("marks", models.IntegerField()),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
    ]
